import type { Student, Company, Job, Application, SavedJob, Resume } from  "../types"

// ============ Mock Student ============
export const mockStudent: Student = {
  id: "student-1",
  email: "john.doe@university.edu",
  fullName: "John Doe",
  phone: "+1 (555) 123-4567",
  college: "State Technical University",
  course: "B.Tech",
  branch: "Computer Science",
  batch: 2024,
  rollNumber: "CS2024001",
  cgpa: 8.5,
  subjects: ["Data Structures", "Algorithms", "Database Systems", "Operating Systems", "Web Development"],
  skills: ["JavaScript", "React", "Node.js", "Python", "SQL", "Git"],
  hasBacklogs: false,
  profilePicture: undefined,
  createdAt: "2023-08-01T00:00:00Z",
  updatedAt: "2024-01-15T00:00:00Z",
};

// ============ Mock Resume ============
export const mockResume: Resume | null = {
  id: "resume-1",
  studentId: "student-1",
  fileName: "John_Doe_Resume.pdf",
  fileUrl: "/resumes/john-doe-resume.pdf",
  fileSize: 245678,
  uploadedAt: "2024-01-10T00:00:00Z",
  updatedAt: "2024-01-15T00:00:00Z",
};

// ============ Mock Companies ============
export const mockCompanies: Company[] = [
  {
    id: "company-1",
    name: "TechCorp Solutions",
    logo: undefined,
    industry: "Information Technology",
    website: "https://techcorp.example.com",
    description: "Leading software development company specializing in enterprise solutions.",
    headquarters: "San Francisco, CA",
  },
  {
    id: "company-2",
    name: "DataFlow Analytics",
    logo: undefined,
    industry: "Data Analytics",
    website: "https://dataflow.example.com",
    description: "Pioneering data analytics and business intelligence solutions.",
    headquarters: "New York, NY",
  },
  {
    id: "company-3",
    name: "CloudNine Systems",
    logo: undefined,
    industry: "Cloud Computing",
    website: "https://cloudnine.example.com",
    description: "Cloud infrastructure and DevOps solutions provider.",
    headquarters: "Seattle, WA",
  },
  {
    id: "company-4",
    name: "FinTech Innovations",
    logo: undefined,
    industry: "Financial Technology",
    website: "https://fintech-innovations.example.com",
    description: "Revolutionary fintech solutions for modern banking.",
    headquarters: "Boston, MA",
  },
  {
    id: "company-5",
    name: "AI Dynamics",
    logo: undefined,
    industry: "Artificial Intelligence",
    website: "https://aidynamics.example.com",
    description: "Cutting-edge AI and machine learning solutions.",
    headquarters: "Austin, TX",
  },
  {
    id: "company-6",
    name: "SecureNet Corp",
    logo: undefined,
    industry: "Cybersecurity",
    website: "https://securenet.example.com",
    description: "Enterprise cybersecurity and threat protection services.",
    headquarters: "Washington, DC",
  },
];

// ============ Mock Jobs ============
export const mockJobs: Job[] = [
  {
    id: "job-1",
    companyId: "company-1",
    company: mockCompanies[0],
    title: "Software Engineer",
    description: "Join our engineering team to build scalable web applications using modern technologies. You'll work on challenging projects that impact millions of users.",
    type: "full-time",
    location: "San Francisco, CA",
    salary: { min: 80000, max: 120000, currency: "USD" },
    eligibility: {
      minCgpa: 7.5,
      branches: ["Computer Science", "Information Technology"],
      batches: [2024, 2025],
      skills: ["JavaScript", "React"],
      noBacklogs: true,
    },
    responsibilities: [
      "Design and develop web applications",
      "Collaborate with cross-functional teams",
      "Write clean, maintainable code",
      "Participate in code reviews",
    ],
    requirements: [
      "Strong problem-solving skills",
      "Experience with React and JavaScript",
      "Understanding of software design patterns",
      "Excellent communication skills",
    ],
    benefits: ["Health insurance", "401(k) matching", "Remote work options", "Professional development"],
    deadline: "2024-03-15T23:59:59Z",
    postedAt: "2024-01-01T00:00:00Z",
    isActive: true,
  },
  {
    id: "job-2",
    companyId: "company-2",
    company: mockCompanies[1],
    title: "Data Analyst",
    description: "Analyze large datasets to derive actionable insights and support data-driven decision making across the organization.",
    type: "full-time",
    location: "New York, NY",
    salary: { min: 70000, max: 100000, currency: "USD" },
    eligibility: {
      minCgpa: 7.0,
      branches: ["Computer Science", "Information Technology", "Mathematics"],
      batches: [2024],
      skills: ["Python", "SQL"],
      noBacklogs: false,
    },
    responsibilities: [
      "Analyze complex datasets",
      "Create data visualizations and reports",
      "Develop statistical models",
      "Present findings to stakeholders",
    ],
    requirements: [
      "Proficiency in Python and SQL",
      "Strong analytical mindset",
      "Experience with data visualization tools",
      "Attention to detail",
    ],
    benefits: ["Competitive salary", "Flexible hours", "Learning budget", "Team events"],
    deadline: "2024-03-20T23:59:59Z",
    postedAt: "2024-01-05T00:00:00Z",
    isActive: true,
  },
  {
    id: "job-3",
    companyId: "company-3",
    company: mockCompanies[2],
    title: "DevOps Engineer",
    description: "Build and maintain CI/CD pipelines, manage cloud infrastructure, and ensure system reliability.",
    type: "full-time",
    location: "Seattle, WA",
    salary: { min: 90000, max: 130000, currency: "USD" },
    eligibility: {
      minCgpa: 8.0,
      branches: ["Computer Science"],
      batches: [2024],
      skills: ["Git", "Python"],
      noBacklogs: true,
    },
    responsibilities: [
      "Design and implement CI/CD pipelines",
      "Manage cloud infrastructure on AWS/GCP",
      "Monitor system performance",
      "Automate operational processes",
    ],
    requirements: [
      "Experience with cloud platforms",
      "Knowledge of containerization",
      "Scripting skills in Python or Bash",
      "Understanding of networking",
    ],
    benefits: ["Stock options", "Health benefits", "Home office stipend", "Unlimited PTO"],
    deadline: "2024-03-25T23:59:59Z",
    postedAt: "2024-01-08T00:00:00Z",
    isActive: true,
  },
  {
    id: "job-4",
    companyId: "company-4",
    company: mockCompanies[3],
    title: "Frontend Developer Intern",
    description: "6-month internship opportunity to learn and grow with our frontend team. Build user interfaces for fintech products.",
    type: "internship",
    location: "Boston, MA",
    salary: { min: 3000, max: 5000, currency: "USD" },
    eligibility: {
      minCgpa: 6.5,
      branches: ["Computer Science", "Information Technology"],
      batches: [2025],
      skills: ["JavaScript"],
      noBacklogs: false,
    },
    responsibilities: [
      "Develop UI components",
      "Write unit tests",
      "Participate in agile ceremonies",
      "Learn from senior developers",
    ],
    requirements: [
      "Basic knowledge of JavaScript",
      "Eagerness to learn",
      "Good communication skills",
      "Team player attitude",
    ],
    benefits: ["Mentorship program", "Certificate", "Pre-placement offer opportunity", "Free meals"],
    deadline: "2024-04-01T23:59:59Z",
    postedAt: "2024-01-10T00:00:00Z",
    isActive: true,
  },
  {
    id: "job-5",
    companyId: "company-5",
    company: mockCompanies[4],
    title: "Machine Learning Engineer",
    description: "Work on cutting-edge ML projects, develop and deploy models for production systems.",
    type: "full-time",
    location: "Austin, TX",
    salary: { min: 100000, max: 150000, currency: "USD" },
    eligibility: {
      minCgpa: 8.5,
      branches: ["Computer Science"],
      batches: [2024],
      skills: ["Python"],
      noBacklogs: true,
    },
    responsibilities: [
      "Design and implement ML models",
      "Optimize model performance",
      "Deploy models to production",
      "Research new ML techniques",
    ],
    requirements: [
      "Strong Python skills",
      "Experience with TensorFlow or PyTorch",
      "Understanding of ML algorithms",
      "Research experience preferred",
    ],
    benefits: ["Top-tier compensation", "Research budget", "Conference attendance", "Gym membership"],
    deadline: "2024-03-30T23:59:59Z",
    postedAt: "2024-01-12T00:00:00Z",
    isActive: true,
  },
  {
    id: "job-6",
    companyId: "company-6",
    company: mockCompanies[5],
    title: "Security Analyst",
    description: "Protect enterprise systems by identifying vulnerabilities and implementing security measures.",
    type: "full-time",
    location: "Washington, DC",
    salary: { min: 85000, max: 115000, currency: "USD" },
    eligibility: {
      minCgpa: 7.5,
      branches: ["Computer Science", "Information Technology"],
      batches: [2024],
      skills: ["Python"],
      noBacklogs: true,
    },
    responsibilities: [
      "Conduct security assessments",
      "Monitor security systems",
      "Respond to security incidents",
      "Develop security policies",
    ],
    requirements: [
      "Knowledge of security frameworks",
      "Experience with security tools",
      "Analytical mindset",
      "Security certifications preferred",
    ],
    benefits: ["Security clearance sponsorship", "Training programs", "Health benefits", "Retirement plan"],
    deadline: "2024-04-05T23:59:59Z",
    postedAt: "2024-01-15T00:00:00Z",
    isActive: true,
  },
  {
    id: "job-7",
    companyId: "company-1",
    company: mockCompanies[0],
    title: "Backend Developer",
    description: "Build robust APIs and backend services that power our enterprise applications.",
    type: "full-time",
    location: "San Francisco, CA (Remote)",
    salary: { min: 85000, max: 125000, currency: "USD" },
    eligibility: {
      minCgpa: 7.0,
      branches: ["Computer Science", "Information Technology"],
      batches: [2024],
      skills: ["Node.js", "SQL"],
      noBacklogs: false,
    },
    responsibilities: [
      "Design and develop APIs",
      "Optimize database queries",
      "Implement authentication systems",
      "Write technical documentation",
    ],
    requirements: [
      "Experience with Node.js",
      "Database design knowledge",
      "API design principles",
      "Problem-solving skills",
    ],
    benefits: ["Remote work", "Health insurance", "Stock options", "Learning stipend"],
    deadline: "2024-03-28T23:59:59Z",
    postedAt: "2024-01-18T00:00:00Z",
    isActive: true,
  },
  {
    id: "job-8",
    companyId: "company-2",
    company: mockCompanies[1],
    title: "Business Intelligence Intern",
    description: "Support the BI team in creating dashboards and analyzing business metrics.",
    type: "internship",
    location: "New York, NY",
    salary: { min: 2500, max: 4000, currency: "USD" },
    eligibility: {
      minCgpa: 6.0,
      branches: ["Computer Science", "Information Technology", "Mathematics", "Business"],
      batches: [2025],
      skills: ["SQL"],
      noBacklogs: false,
    },
    responsibilities: [
      "Create data visualizations",
      "Assist in report generation",
      "Learn BI tools",
      "Support data quality efforts",
    ],
    requirements: [
      "Basic SQL knowledge",
      "Excel proficiency",
      "Analytical thinking",
      "Attention to detail",
    ],
    benefits: ["Hands-on experience", "Networking opportunities", "Flexible schedule", "Mentorship"],
    deadline: "2024-04-10T23:59:59Z",
    postedAt: "2024-01-20T00:00:00Z",
    isActive: true,
  },
  {
    id: "job-9",
    companyId: "company-3",
    company: mockCompanies[2],
    title: "Cloud Solutions Architect",
    description: "Design and implement cloud solutions for enterprise clients across various industries.",
    type: "full-time",
    location: "Seattle, WA",
    salary: { min: 120000, max: 170000, currency: "USD" },
    eligibility: {
      minCgpa: 8.0,
      branches: ["Computer Science"],
      batches: [2024],
      skills: ["Python", "Git"],
      noBacklogs: true,
    },
    responsibilities: [
      "Design cloud architectures",
      "Lead technical implementations",
      "Consult with clients",
      "Mentor junior engineers",
    ],
    requirements: [
      "Cloud certifications (AWS/GCP/Azure)",
      "5+ years equivalent experience",
      "Strong communication skills",
      "Leadership abilities",
    ],
    benefits: ["Premium compensation", "Executive benefits", "Company car", "Annual bonus"],
    deadline: "2024-03-22T23:59:59Z",
    postedAt: "2024-01-22T00:00:00Z",
    isActive: true,
  },
  {
    id: "job-10",
    companyId: "company-5",
    company: mockCompanies[4],
    title: "AI Research Intern",
    description: "Contribute to cutting-edge AI research projects under the guidance of our research team.",
    type: "internship",
    location: "Austin, TX",
    salary: { min: 4000, max: 6000, currency: "USD" },
    eligibility: {
      minCgpa: 9.0,
      branches: ["Computer Science"],
      batches: [2025],
      skills: ["Python"],
      noBacklogs: true,
    },
    responsibilities: [
      "Conduct literature reviews",
      "Implement research papers",
      "Run experiments",
      "Co-author publications",
    ],
    requirements: [
      "Strong academic record",
      "Research experience",
      "Deep learning knowledge",
      "Publication experience preferred",
    ],
    benefits: ["Research credits", "Publication opportunity", "Full-time offer potential", "Conference travel"],
    deadline: "2024-04-15T23:59:59Z",
    postedAt: "2024-01-25T00:00:00Z",
    isActive: true,
  },
];

// ============ Mock Applications ============
export const mockApplications: Application[] = [
  {
    id: "app-1",
    studentId: "student-1",
    jobId: "job-1",
    job: mockJobs[0],
    status: "shortlisted",
    appliedAt: "2024-01-15T10:30:00Z",
    updatedAt: "2024-01-20T14:00:00Z",
    statusHistory: [
      { status: "applied", timestamp: "2024-01-15T10:30:00Z" },
      { status: "shortlisted", timestamp: "2024-01-20T14:00:00Z", note: "Congratulations! You've been shortlisted for the next round." },
    ],
  },
  {
    id: "app-2",
    studentId: "student-1",
    jobId: "job-2",
    job: mockJobs[1],
    status: "interview",
    appliedAt: "2024-01-10T09:00:00Z",
    updatedAt: "2024-01-25T11:00:00Z",
    statusHistory: [
      { status: "applied", timestamp: "2024-01-10T09:00:00Z" },
      { status: "shortlisted", timestamp: "2024-01-18T10:00:00Z" },
      { status: "interview", timestamp: "2024-01-25T11:00:00Z", note: "Interview scheduled for Feb 5, 2024 at 2:00 PM." },
    ],
  },
  {
    id: "app-3",
    studentId: "student-1",
    jobId: "job-6",
    job: mockJobs[5],
    status: "applied",
    appliedAt: "2024-01-28T15:45:00Z",
    updatedAt: "2024-01-28T15:45:00Z",
    statusHistory: [
      { status: "applied", timestamp: "2024-01-28T15:45:00Z" },
    ],
  },
];

// ============ Mock Saved Jobs ============
export const mockSavedJobs: SavedJob[] = [
  {
    id: "saved-1",
    studentId: "student-1",
    jobId: "job-3",
    savedAt: "2024-01-20T08:00:00Z",
  },
  {
    id: "saved-2",
    studentId: "student-1",
    jobId: "job-5",
    savedAt: "2024-01-22T12:30:00Z",
  },
];