import type {
  Opportunity,
  Company,
  RecruiterOutreach,
  CompanyHeadline,
  MockInterviewRecord,
  AlumniRecord,
  Announcement,
  AdminUser,
  ReviewJob,
} from "../types";

// Mock Opportunities
export const mockOpportunities: Opportunity[] = [
  {
    id: "opp-1",
    companyName: "Google",
    roleTitle: "Software Engineer",
    type: "full-time",
    requiredSkills: ["JavaScript", "Python", "System Design"],
    eligibility: { branches: ["CSE", "IT", "ECE"], minCgpa: 7.5 },
    deadline: "2026-02-15",
    location: "Bangalore",
    mode: "hybrid",
    ctc: { min: 2500000, max: 3500000 },
    source: "manual",
    status: "approved",
    postedDate: "2026-01-20",
    description: "Join Google's engineering team",
  },
  {
    id: "opp-2",
    companyName: "Microsoft",
    roleTitle: "SDE Intern",
    type: "internship",
    requiredSkills: ["C++", "Data Structures", "Algorithms"],
    eligibility: { branches: ["CSE", "IT"], minCgpa: 8.0 },
    deadline: "2026-02-28",
    location: "Hyderabad",
    mode: "on-site",
    ctc: { min: 50000, max: 75000 },
    source: "linkedin",
    status: "pending",
    postedDate: "2026-01-25",
  },
  {
    id: "opp-3",
    companyName: "Amazon",
    roleTitle: "Cloud Solutions Architect",
    type: "full-time",
    requiredSkills: ["AWS", "Cloud Computing", "DevOps"],
    eligibility: { branches: ["CSE", "IT", "ECE", "EE"], minCgpa: 7.0 },
    deadline: "2026-03-10",
    location: "Gurgaon",
    mode: "remote",
    ctc: { min: 2000000, max: 2800000 },
    source: "naukri",
    status: "approved",
    postedDate: "2026-01-28",
  },
  {
    id: "opp-4",
    companyName: "TCS",
    roleTitle: "Graduate Trainee",
    type: "full-time",
    requiredSkills: ["Java", "SQL", "Communication"],
    eligibility: { branches: ["CSE", "IT", "ECE", "EE", "ME", "CE"], minCgpa: 6.0 },
    deadline: "2026-02-20",
    location: "Mumbai",
    mode: "on-site",
    ctc: { min: 400000, max: 700000 },
    source: "manual",
    status: "approved",
    postedDate: "2026-01-15",
  },
  {
    id: "opp-5",
    companyName: "Flipkart",
    roleTitle: "Product Manager Intern",
    type: "internship",
    requiredSkills: ["Product Thinking", "Analytics", "Communication"],
    eligibility: { branches: ["CSE", "IT", "MBA"], minCgpa: 7.5 },
    deadline: "2026-02-10",
    location: "Bangalore",
    mode: "hybrid",
    ctc: { min: 40000, max: 60000 },
    source: "internshala",
    status: "pending",
    postedDate: "2026-01-30",
  },
];

// Mock Companies
export const mockCompanies: Company[] = [
  {
    id: "comp-1",
    name: "Google",
    industry: "Technology",
    website: "https://google.com",
    location: "Bangalore, India",
    hrContacts: [
      { name: "Priya Sharma", email: "priya@google.com", phone: "+91-9876543210", designation: "HR Manager" },
    ],
    lastContactedDate: "2026-01-25",
    contactStatus: "active",
    pastHiringHistory: [
      { year: 2025, rolesOffered: ["SDE", "SRE"], studentsHired: 12, avgPackage: 3200000 },
      { year: 2024, rolesOffered: ["SDE"], studentsHired: 8, avgPackage: 2800000 },
    ],
    averageCTC: 3000000,
    notes: "Top recruiter, prefers DSA-focused candidates",
  },
  {
    id: "comp-2",
    name: "Microsoft",
    industry: "Technology",
    website: "https://microsoft.com",
    location: "Hyderabad, India",
    hrContacts: [
      { name: "Rahul Verma", email: "rahul@microsoft.com", phone: "+91-9876543211", designation: "Campus Lead" },
    ],
    lastContactedDate: "2026-01-20",
    contactStatus: "active",
    pastHiringHistory: [
      { year: 2025, rolesOffered: ["SDE", "PM"], studentsHired: 15, avgPackage: 2800000 },
    ],
    averageCTC: 2800000,
    notes: "Strong preference for competitive programmers",
  },
  {
    id: "comp-3",
    name: "Amazon",
    industry: "E-commerce/Technology",
    website: "https://amazon.com",
    location: "Gurgaon, India",
    hrContacts: [
      { name: "Ananya Singh", email: "ananya@amazon.com", phone: "+91-9876543212", designation: "Talent Acquisition" },
    ],
    lastContactedDate: "2026-01-28",
    contactStatus: "active",
    pastHiringHistory: [
      { year: 2025, rolesOffered: ["SDE", "Cloud Engineer"], studentsHired: 20, avgPackage: 2500000 },
    ],
    averageCTC: 2500000,
    notes: "Multiple rounds of technical interviews",
  },
  {
    id: "comp-4",
    name: "TCS",
    industry: "IT Services",
    website: "https://tcs.com",
    location: "Mumbai, India",
    hrContacts: [
      { name: "Vikram Patel", email: "vikram@tcs.com", phone: "+91-9876543213", designation: "HR Executive" },
    ],
    lastContactedDate: "2026-01-15",
    contactStatus: "active",
    pastHiringHistory: [
      { year: 2025, rolesOffered: ["Graduate Trainee"], studentsHired: 100, avgPackage: 500000 },
    ],
    averageCTC: 500000,
    notes: "Mass recruiter, focuses on aptitude",
  },
  {
    id: "comp-5",
    name: "Infosys",
    industry: "IT Services",
    website: "https://infosys.com",
    location: "Pune, India",
    hrContacts: [
      { name: "Meera Nair", email: "meera@infosys.com", phone: "+91-9876543214", designation: "Campus Relations" },
    ],
    lastContactedDate: "2026-01-10",
    contactStatus: "inactive",
    pastHiringHistory: [
      { year: 2025, rolesOffered: ["Systems Engineer"], studentsHired: 80, avgPackage: 450000 },
    ],
    averageCTC: 450000,
    notes: "Follow up needed for 2026 drive",
  },
];

// Mock Recruiter Outreach
export const mockOutreach: RecruiterOutreach[] = [
  {
    id: "out-1",
    companyName: "Google",
    recruiterName: "Priya Sharma",
    contactMode: "email",
    dateTime: "2026-01-25T10:30:00",
    summary: "Discussed 2026 campus hiring timeline. Confirmed visit in March.",
    nextFollowUpDate: "2026-02-10",
    status: "responded",
  },
  {
    id: "out-2",
    companyName: "Microsoft",
    recruiterName: "Rahul Verma",
    contactMode: "call",
    dateTime: "2026-01-20T14:00:00",
    summary: "Shared student profiles. Waiting for shortlist.",
    nextFollowUpDate: "2026-02-05",
    status: "pending",
  },
  {
    id: "out-3",
    companyName: "Amazon",
    recruiterName: "Ananya Singh",
    contactMode: "meeting",
    dateTime: "2026-01-28T11:00:00",
    summary: "In-person meeting at campus. Finalized JD and eligibility criteria.",
    nextFollowUpDate: "2026-02-15",
    status: "responded",
  },
  {
    id: "out-4",
    companyName: "Infosys",
    recruiterName: "Meera Nair",
    contactMode: "email",
    dateTime: "2026-01-10T09:00:00",
    summary: "Initial outreach for 2026 hiring. No response yet.",
    nextFollowUpDate: "2026-01-31",
    status: "follow-up",
  },
];

// Mock Company Headlines
export const mockHeadlines: CompanyHeadline[] = [
  {
    id: "head-1",
    companyName: "Google",
    headline: "Google Campus Hiring Drive 2026",
    date: "2026-03-15",
    rolesOffered: ["Software Engineer", "Site Reliability Engineer"],
    selectionRatio: 0.15,
    announcement: "Google to visit campus for 2026 batch placements",
  },
  {
    id: "head-2",
    companyName: "Microsoft",
    headline: "Microsoft Internship Program 2026",
    date: "2026-02-20",
    rolesOffered: ["SDE Intern", "PM Intern"],
    selectionRatio: 0.12,
    announcement: "Applications open for summer internship program",
  },
  {
    id: "head-3",
    companyName: "TCS",
    headline: "TCS Mass Recruitment 2026",
    date: "2026-02-25",
    rolesOffered: ["Graduate Trainee", "Digital Specialist"],
    selectionRatio: 0.65,
    announcement: "TCS hiring 100+ students from campus",
  },
];

// Mock Interview Records
export const mockInterviews: MockInterviewRecord[] = [
  {
    id: "int-1",
    studentName: "Aarav Kumar",
    studentId: "STU001",
    interviewType: "technical",
    status: "completed",
    scheduledDate: "2026-01-28",
    aiScore: 78,
    communicationScore: 72,
    technicalScore: 82,
    resumeScore: 85,
    suggestions: ["Practice system design", "Improve communication pace"],
  },
  {
    id: "int-2",
    studentName: "Priya Singh",
    studentId: "STU002",
    interviewType: "hr",
    status: "completed",
    scheduledDate: "2026-01-27",
    aiScore: 85,
    communicationScore: 90,
    technicalScore: 75,
    resumeScore: 88,
    suggestions: ["Strengthen technical fundamentals"],
  },
  {
    id: "int-3",
    studentName: "Rohit Sharma",
    studentId: "STU003",
    interviewType: "technical",
    status: "scheduled",
    scheduledDate: "2026-02-02",
  },
  {
    id: "int-4",
    studentName: "Sneha Patel",
    studentId: "STU004",
    interviewType: "role-specific",
    status: "completed",
    scheduledDate: "2026-01-26",
    aiScore: 92,
    communicationScore: 88,
    technicalScore: 94,
    resumeScore: 90,
    suggestions: ["Excellent performance, ready for interviews"],
  },
];

// Mock Alumni
export const mockAlumni: AlumniRecord[] = [
  {
    id: "alum-1",
    name: "Vikram Malhotra",
    graduationYear: 2022,
    company: "Google",
    role: "Senior Software Engineer",
    email: "vikram.m@gmail.com",
    phone: "+91-9876543220",
    willingToRefer: true,
    pastReferrals: 5,
    engagementStatus: "active",
  },
  {
    id: "alum-2",
    name: "Neha Gupta",
    graduationYear: 2021,
    company: "Microsoft",
    role: "Product Manager",
    email: "neha.g@outlook.com",
    willingToRefer: true,
    pastReferrals: 3,
    engagementStatus: "active",
  },
  {
    id: "alum-3",
    name: "Arjun Reddy",
    graduationYear: 2023,
    company: "Amazon",
    role: "SDE-1",
    email: "arjun.r@yahoo.com",
    willingToRefer: true,
    pastReferrals: 2,
    engagementStatus: "active",
  },
  {
    id: "alum-4",
    name: "Kavya Nair",
    graduationYear: 2020,
    company: "Flipkart",
    role: "Engineering Manager",
    email: "kavya.n@gmail.com",
    willingToRefer: false,
    pastReferrals: 8,
    engagementStatus: "inactive",
  },
];

// Mock Announcements
export const mockAnnouncements: Announcement[] = [
  {
    id: "ann-1",
    type: "job",
    title: "Google Campus Drive 2026",
    content: "Google will be conducting campus placements on March 15, 2026. Eligible students should apply before the deadline.",
    targetAudience: ["CSE", "IT", "ECE"],
    publishDate: "2026-01-30",
    expiryDate: "2026-03-14",
    status: "published",
  },
  {
    id: "ann-2",
    type: "training",
    title: "DSA Workshop Series",
    content: "3-day intensive DSA workshop starting February 5th. Register now!",
    targetAudience: ["All"],
    publishDate: "2026-01-28",
    expiryDate: "2026-02-04",
    status: "published",
  },
  {
    id: "ann-3",
    type: "result",
    title: "TCS Selection Results",
    content: "Results for TCS campus drive have been announced. Check your email for details.",
    targetAudience: ["CSE", "IT", "ECE", "EE", "ME"],
    publishDate: "2026-01-25",
    expiryDate: "2026-02-25",
    status: "published",
  },
  {
    id: "ann-4",
    type: "notice",
    title: "Resume Submission Deadline",
    content: "All students must submit updated resumes by February 1st for the upcoming placement season.",
    targetAudience: ["All"],
    publishDate: "2026-01-20",
    expiryDate: "2026-02-01",
    status: "published",
  },
];

// Mock Admin Users
export const mockAdminUsers: AdminUser[] = [
  {
    id: "usr-1",
    name: "Dr. Sharma",
    email: "tnp.head@college.edu",
    phone: "+91-9876543210",
    department: "Computer Science",
    role: "super_admin",
    permissions: ["all"],
    lastLogin: "2026-01-31T10:00:00",
    lastActive: "2026-01-31T10:00:00",
    status: "active",
  },
  {
    id: "usr-2",
    name: "Prof. Verma",
    email: "tnp.coord@college.edu",
    phone: "+91-9876543211",
    department: "Electronics",
    role: "admin",
    permissions: ["opportunities", "companies", "students", "reports"],
    lastLogin: "2026-01-31T09:30:00",
    lastActive: "2026-01-31T09:30:00",
    status: "active",
  },
  {
    id: "usr-3",
    name: "Mr. Patel",
    email: "placement.asst@college.edu",
    department: "Mechanical",
    role: "coordinator",
    permissions: ["opportunities", "announcements"],
    lastLogin: "2026-01-30T16:00:00",
    lastActive: "2026-01-30T16:00:00",
    status: "active",
  },
  {
    id: "usr-4",
    name: "Ms. Gupta",
    email: "viewer@college.edu",
    role: "viewer",
    permissions: ["view_only"],
    lastActive: "2026-01-29T14:00:00",
    status: "inactive",
  },
];

// Mock Review Jobs
export const mockReviewJobs: ReviewJob[] = [
  {
    id: "rev-1",
    submittedBy: "Vikram Malhotra (Alumni)",
    submitterType: "alumni",
    opportunityDetails: {
      companyName: "Stripe",
      roleTitle: "Backend Engineer",
      type: "full-time",
      ctc: { min: 3000000, max: 4000000 },
      location: "Bangalore",
    },
    credibilityScore: 95,
    verificationStatus: "pending",
  },
  {
    id: "rev-2",
    submittedBy: "Prof. Singh (Faculty)",
    submitterType: "faculty",
    opportunityDetails: {
      companyName: "DRDO",
      roleTitle: "Scientist-B",
      type: "full-time",
      ctc: { min: 800000, max: 1000000 },
      location: "Delhi",
    },
    credibilityScore: 100,
    verificationStatus: "verified",
    adminNotes: "Government opportunity, highly credible",
  },
  {
    id: "rev-3",
    submittedBy: "External Referral",
    submitterType: "external",
    opportunityDetails: {
      companyName: "StartupXYZ",
      roleTitle: "Full Stack Developer",
      type: "full-time",
      ctc: { min: 1200000, max: 1800000 },
      location: "Remote",
    },
    credibilityScore: 60,
    verificationStatus: "pending",
    adminNotes: "Need to verify company credentials",
  },
];

// Dashboard Stats
export const mockDashboardStats = {
  activeJobs: 24,
  activeInternships: 12,
  totalCompanies: 45,
  registeredStudents: 850,
  eligibleStudents: 720,
  offersMade: 156,
  offersAccepted: 142,
  pendingFollowUps: 8,
  upcomingDeadlines: [
    { company: "Google", role: "SDE", deadline: "2026-02-15" },
    { company: "Microsoft", role: "Intern", deadline: "2026-02-28" },
    { company: "Flipkart", role: "PM Intern", deadline: "2026-02-10" },
  ],
  alerts: [
    { type: "warning", message: "5 jobs have low applications (<10)" },
    { type: "info", message: "3 jobs expiring this week" },
    { type: "success", message: "New company onboarded: Stripe" },
  ],
  topHiringCompanies: [
    { name: "TCS", hires: 100 },
    { name: "Amazon", hires: 20 },
    { name: "Google", hires: 12 },
    { name: "Microsoft", hires: 15 },
  ],
  monthlyTrend: [
    { month: "Sep", placements: 15 },
    { month: "Oct", placements: 45 },
    { month: "Nov", placements: 78 },
    { month: "Dec", placements: 95 },
    { month: "Jan", placements: 142 },
  ],
  topSkills: [
    { skill: "JavaScript", demand: 85 },
    { skill: "Python", demand: 80 },
    { skill: "React", demand: 75 },
    { skill: "AWS", demand: 70 },
    { skill: "SQL", demand: 68 },
  ],
};
